export enum WorkspaceEvent {
  WORKSPACE_CREATED = "WORKSPACE_CREATED",
  WORKSPACE_UPDATED = "WORKSPACE_UPDATED",
  WORKSPACE_DELETED = "WORKSPACE_DELETED",
  WORKSPACE_SWITCHED = "WORKSPACE_SWITCHED",
  MEMBER_INVITED = "MEMBER_INVITED",
  MEMBER_JOINED = "MEMBER_JOINED",
  MEMBER_REMOVED = "MEMBER_REMOVED",
  MEMBER_ROLE_UPDATED = "MEMBER_ROLE_UPDATED",
  INVITATION_ACCEPTED = "INVITATION_ACCEPTED",
  INVITATION_REJECTED = "INVITATION_REJECTED",
  INVITATION_CANCELLED = "INVITATION_CANCELLED",
}
