export enum ProfileEvent {
  PROFILE_UPDATED = "PROFILE_UPDATED",
  AVATAR_CHANGED = "AVATAR_CHANGED",
  AVATAR_REMOVED = "AVATAR_REMOVED",
  PREFERENCES_UPDATED = "PREFERENCES_UPDATED",
  SESSION_TERMINATED = "SESSION_TERMINATED",
  DEVICE_REFRESHED = "DEVICE_REFRESHED",
}
