import { colors } from "./colors";

export const semanticColors = {
  light: {
    background: "#ffffff",
    foreground: colors.navyBlue[900],
    primary: colors.primaryBlue[600],
    primaryForeground: "#ffffff",
    secondary: colors.navyBlue[100],
    secondaryForeground: colors.navyBlue[900],
    surface: "#ffffff",
    surfaceHover: colors.navyBlue[50],
    border: colors.navyBlue[200],
    success: "#10b981", // emerald-500
    warning: "#f59e0b", // amber-500
    danger: "#ef4444", // red-500
    info: colors.skyBlue[500],
    textPrimary: colors.navyBlue[900],
    textSecondary: colors.navyBlue[500],
    textMuted: colors.navyBlue[400],
    disabled: colors.navyBlue[200],
    overlay: "rgba(15, 23, 42, 0.5)",
    card: "#ffffff",
    popover: "#ffffff",
    accent: colors.navyBlue[100],
    muted: colors.navyBlue[100],
    destructive: "#ef4444",
  },
  dark: {
    background: colors.navyBlue[900],
    foreground: colors.navyBlue[50],
    primary: colors.primaryBlue[500],
    primaryForeground: "#ffffff",
    secondary: colors.navyBlue[800],
    secondaryForeground: colors.navyBlue[50],
    surface: colors.navyBlue[800],
    surfaceHover: colors.navyBlue[700],
    border: colors.navyBlue[700],
    success: "#10b981",
    warning: "#f59e0b",
    danger: "#ef4444",
    info: colors.skyBlue[500],
    textPrimary: colors.navyBlue[50],
    textSecondary: colors.navyBlue[300],
    textMuted: colors.navyBlue[400],
    disabled: colors.navyBlue[700],
    overlay: "rgba(0, 0, 0, 0.7)",
    card: colors.navyBlue[800],
    popover: colors.navyBlue[800],
    accent: colors.navyBlue[700],
    muted: colors.navyBlue[800],
    destructive: "#ef4444",
  },
};
