export enum SecurityEventAction {
  SESSION_CREATED = "SESSION_CREATED",
  SESSION_TERMINATED = "SESSION_TERMINATED",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILED = "LOGIN_FAILED",
  PASSWORD_CHANGED = "PASSWORD_CHANGED",
  EMAIL_VERIFIED = "EMAIL_VERIFIED",
  SECURITY_SCORE_UPDATED = "SECURITY_SCORE_UPDATED",
  DEVICE_TRUSTED = "DEVICE_TRUSTED",
  DEVICE_REMOVED = "DEVICE_REMOVED",
}
