export enum AuthEvent {
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILED = "LOGIN_FAILED",
  LOGOUT = "LOGOUT",
  SESSION_REFRESHED = "SESSION_REFRESHED",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  PASSWORD_RESET = "PASSWORD_RESET",
  EMAIL_VERIFIED = "EMAIL_VERIFIED",
}
