export enum AuthorizationEvent {
  ROLE_ASSIGNED = "ROLE_ASSIGNED",
  ROLE_REMOVED = "ROLE_REMOVED",
  PERMISSION_GRANTED = "PERMISSION_GRANTED",
  PERMISSION_REVOKED = "PERMISSION_REVOKED",
  ACCESS_DENIED = "ACCESS_DENIED",
  ACCESS_GRANTED = "ACCESS_GRANTED",
}
