import { Role } from "./types";
import { ROLE_PRIORITIES } from "./constants";

export const DefaultRoles: Record<string, Role> = {
  OWNER: {
    id: "role-owner",
    name: "Owner",
    description: "Workspace owner with full access to everything including billing and deletion.",
    priority: ROLE_PRIORITIES.OWNER,
    system: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  ADMIN: {
    id: "role-admin",
    name: "Admin",
    description: "Administrator with full access except destructive workspace actions.",
    priority: ROLE_PRIORITIES.ADMIN,
    system: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  EDITOR: {
    id: "role-editor",
    name: "Editor",
    description: "Can create, edit, and publish content but cannot manage users or settings.",
    priority: ROLE_PRIORITIES.EDITOR,
    system: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  VIEWER: {
    id: "role-viewer",
    name: "Viewer",
    description: "Can view content and analytics only.",
    priority: ROLE_PRIORITIES.VIEWER,
    system: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  GUEST: {
    id: "role-guest",
    name: "Guest",
    description: "External guest with limited access to specific shared resources.",
    priority: ROLE_PRIORITIES.GUEST,
    system: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  SYSTEM: {
    id: "role-system",
    name: "System",
    description: "Internal system role for background jobs and webhooks.",
    priority: ROLE_PRIORITIES.SYSTEM,
    system: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
};

// Map of which roles get which permissions by default.
// This will be used by the Mock Repository or Database seed scripts.
export const RolePermissionMap: Record<string, string[]> = {
  "role-owner": ["*"],
  "role-admin": [
    "invitation:*",
    "guest:*",
    "template:*",
    "marketplace:*",
    "analytics:*",
    "notification:*",
    "publishing:*",
    "builder:*",
    "profile:*",
    "workspace:read",
    "workspace:update",
  ],
  "role-editor": [
    "invitation:read",
    "invitation:update",
    "invitation:create",
    "guest:read",
    "guest:update",
    "guest:create",
    "template:read",
    "template:update",
    "template:create",
    "publishing:read",
    "publishing:publish",
    "builder:read",
    "builder:update",
    "builder:create",
    "profile:read",
    "profile:update",
    "analytics:read",
  ],
  "role-viewer": [
    "invitation:read",
    "guest:read",
    "template:read",
    "analytics:read",
    "publishing:read",
    "builder:read",
    "profile:read",
  ],
  "role-guest": ["profile:read", "profile:update"],
  "role-system": ["*"],
};
